# Usefull links
# =============
# https://hub.docker.com/_/php/
# https://docs.docker.com/compose/overview/
# https://docs.docker.com/compose/compose-file/
#
# Usefull commands
# ================
#
# Start containers
# $ docker-compose up -d
#
# View running containers
# $ docker-compose ps
#
# Connect into command line of running container
# $ docker-compose run <container_name> bash
# where <name> could be db_incom, etc.
# Tip: `Ctrl+p` + `Ctrl+q` + `Enter` (to exit container bash)
#
# View docker logs
# $ docker-compose logs
#
# Stop containers
# $ docker-compose down
#
# Remove images
# $ docker rmi limoncelloflute_fpm
#
# Run non-default docker-compose file
# $ docker-compose -f <file_name.yml> up -d
# $ docker-compose -f <file_name.yml> down
# $ docker-compose -f <file_name.yml> stop

version: '3.7'

services:
  php:
    image: neomerx/ip2i-service-alpine
    container_name: ip2i_service

  nginx:
    image: neomerx/ip2i-web
    container_name: ip2i_web
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - target: 80
        published: 8080
    depends_on:
      - php
    links:
      - php
